import { obiItemStack, obuVector, obLocation, obePlayer, obuBoundingBox, obbBlock, obeEntity, obOfflinePlayer } from '@grakkit/types-paper';
import { Parser, SerializedBoundingBox, SerializedEntity, SerializedItemStack, SerializedLocation, SerializedVector, Serializer } from './spec';
export declare type HasBoundingBox = obuBoundingBox | SerializedBoundingBox | IsPhysical;
export declare type HasItemStack = obiItemStack | SerializedItemStack | IsPhysical;
export declare type HasLocation = obLocation | SerializedLocation | IsPhysical;
export declare type HasVector = obuVector | SerializedVector | HasLocation;
export declare type IsEntity = obeEntity | obePlayer | obOfflinePlayer;
export declare type IsPhysical = obbBlock | IsEntity | SerializedEntity;
export declare const data: (arg1: IsPhysical, arg2?: string) => any;
export declare const parse: Parser;
export declare const serialize: Serializer;
